[package]
name = "rsslite"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
reqwest = "0.12.23"
rss = "2.0.12"
rusqlite = "0.37.0"
thiserror = "2.0.17"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
