//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rss_channel")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    #[sea_orm(unique)]
    pub link: String,
    pub description: String,
    pub language: Option<String>,
    pub copyright: Option<String>,
    pub managing_editor: Option<String>,
    pub webmaster: Option<String>,
    pub pub_date: Option<String>,
    pub last_build_date: Option<String>,
    pub generator: Option<String>,
    pub docs: Option<String>,
    pub cloud: Option<String>,
    pub rating: Option<String>,
    pub ttl: Option<String>,
    pub image: Option<String>,
    pub text_input: Option<String>,
    pub categories: Option<String>,
    pub skip_hours: Option<String>,
    pub skip_days: Option<String>,
    pub items: Option<String>,
    pub extensions: Option<String>,
    pub itunes_ext: Option<String>,
    pub dublin_core_ext: Option<String>,
    pub syndication_ext: Option<String>,
    pub namespaces: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
