//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rss_category")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub channel_id: Option<i32>,
    pub item_id: Option<i32>,
    pub name: String,
    pub domain: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::rss_channel::Entity",
        from = "Column::ChannelId",
        to = "super::rss_channel::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    RssChannel,
    #[sea_orm(
        belongs_to = "super::rss_item::Entity",
        from = "Column::ItemId",
        to = "super::rss_item::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    RssItem,
}

impl Related<super::rss_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RssChannel.def()
    }
}

impl Related<super::rss_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RssItem.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
