//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rss_item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: Option<String>,
    #[sea_orm(unique)]
    pub link: String,
    pub description: Option<String>,
    pub author: Option<String>,
    pub categories: Option<String>,
    pub comments: Option<String>,
    pub enclosure_url: Option<String>,
    pub enclosure_length: Option<String>,
    pub enclosure_mime_type: Option<String>,
    pub guid: Option<String>,
    pub pub_date: Option<String>,
    pub source_title: Option<String>,
    pub source_url: Option<String>,
    pub content: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
