//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rss_dublin_core_ext")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub item_id: i32,
    pub contributors: Json,
    pub coverages: Json,
    pub creators: Json,
    pub dates: Json,
    pub descriptions: Json,
    pub formats: Json,
    pub identifiers: Json,
    pub languages: Json,
    pub publishers: Json,
    pub relations: Json,
    pub rights: Json,
    pub sources: Json,
    pub subjects: Json,
    pub titles: Json,
    pub types: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::rss_item::Entity",
        from = "Column::ItemId",
        to = "super::rss_item::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    RssItem,
}

impl Related<super::rss_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RssItem.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
