[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dotenv = "0.15.0"
sea-orm = "1.1.17"
thiserror = "2.0.17"
chrono = "0.4"
tracing-subscriber = "0.3"
tokio = { version = "1.47.1", features = ["rt"] }
models = { path = "../models" }
